# Generated by Django 3.2.9 on 2021-12-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapaAccesoDatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria_Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='auditoria',
        ),
    ]
