# Generated by Django 3.2.9 on 2021-12-17 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CapaAccesoDatos', '0002_auto_20211217_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalt_voto',
            fields=[
                ('id_voto', models.IntegerField(blank=True, db_index=True)),
                ('tipo_voto', models.CharField(max_length=50)),
                ('voto_fecha', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_partido', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='CapaAccesoDatos.t_partido')),
            ],
            options={
                'verbose_name': 'historical t_voto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
